export type PhoneCountryMetadata = {
    lengths: number[]
    groups: number[]
}

export const PHONE_METADATA: Record<string, PhoneCountryMetadata> = {
    AC: { lengths: [5], groups: [3, 3, 1] },
    AD: { lengths: [6, 9], groups: [3, 3] },
    AE: { lengths: [9], groups: [3, 1, 5] },
    AF: { lengths: [9], groups: [2, 3, 4] },
    AG: { lengths: [10], groups: [3, 3, 4] },
    AI: { lengths: [10], groups: [3, 3, 4] },
    AL: { lengths: [9], groups: [2, 3, 4] },
    AM: { lengths: [8], groups: [3, 2, 3] },
    AO: { lengths: [9], groups: [3, 3, 3] },
    AR: { lengths: [10], groups: [4, 2, 4] },
    AS: { lengths: [10], groups: [3, 3, 4] },
    AT: { lengths: [7, 8, 9, 10, 11, 12, 13], groups: [2, 5] },
    AU: { lengths: [9], groups: [3, 3, 3] },
    AW: { lengths: [7], groups: [3, 4] },
    AX: { lengths: [6, 7, 8, 9, 10], groups: [3, 3, 4] },
    AZ: { lengths: [9], groups: [3, 2, 2, 2] },
    BA: { lengths: [8], groups: [2, 3, 3] },
    BB: { lengths: [10], groups: [3, 3, 4] },
    BD: { lengths: [10], groups: [3, 7] },
    BE: { lengths: [9], groups: [3, 2, 2, 2] },
    BF: { lengths: [8], groups: [2, 2, 2, 2] },
    BG: { lengths: [8, 9], groups: [1, 3, 4] },
    BH: { lengths: [8], groups: [4, 4] },
    BI: { lengths: [8], groups: [2, 2, 2, 2] },
    BJ: { lengths: [10], groups: [2, 2, 2, 2, 2] },
    BL: { lengths: [9], groups: [3, 3, 3] },
    BM: { lengths: [10], groups: [3, 3, 4] },
    BN: { lengths: [7], groups: [3, 4] },
    BO: { lengths: [8], groups: [1, 7] },
    BQ: { lengths: [7], groups: [3, 3, 1] },
    BR: { lengths: [10, 11], groups: [3, 3, 4] },
    BS: { lengths: [10], groups: [3, 3, 4] },
    BT: { lengths: [8], groups: [2, 2, 2, 2] },
    BW: { lengths: [8], groups: [2, 3, 3] },
    BY: { lengths: [9], groups: [3, 2, 4] },
    BZ: { lengths: [7], groups: [3, 4] },
    CA: { lengths: [10], groups: [3, 3, 4] },
    CC: { lengths: [9], groups: [3, 3, 3] },
    CD: { lengths: [7, 9], groups: [2, 2, 3] },
    CF: { lengths: [8], groups: [2, 2, 2, 2] },
    CG: { lengths: [9], groups: [1, 4, 4] },
    CH: { lengths: [9], groups: [3, 3, 3] },
    CI: { lengths: [10], groups: [2, 2, 1, 5] },
    CK: { lengths: [5], groups: [2, 3] },
    CL: { lengths: [9], groups: [5, 4] },
    CM: { lengths: [9], groups: [1, 2, 2, 2, 2] },
    CN: { lengths: [11], groups: [3, 8] },
    CO: { lengths: [10], groups: [3, 7] },
    CR: { lengths: [8], groups: [4, 4] },
    CU: { lengths: [8], groups: [2, 6] },
    CV: { lengths: [7], groups: [3, 2, 2] },
    CW: { lengths: [7, 8], groups: [3, 4] },
    CX: { lengths: [9], groups: [3, 3, 3] },
    CY: { lengths: [8], groups: [2, 6] },
    CZ: { lengths: [9], groups: [3, 3, 3] },
    DE: { lengths: [10, 11], groups: [3, 8] },
    DJ: { lengths: [8], groups: [2, 2, 2, 2] },
    DK: { lengths: [8], groups: [2, 2, 2, 2] },
    DM: { lengths: [10], groups: [3, 3, 4] },
    DO: { lengths: [10], groups: [3, 3, 4] },
    DZ: { lengths: [9], groups: [2, 3, 2, 2] },
    EC: { lengths: [9], groups: [2, 3, 4] },
    EE: { lengths: [7, 8], groups: [3, 4] },
    EG: { lengths: [10], groups: [3, 3, 4] },
    EH: { lengths: [9], groups: [3, 3, 3] },
    ER: { lengths: [7], groups: [1, 3, 3] },
    ES: { lengths: [9], groups: [3, 3, 3] },
    ET: { lengths: [9], groups: [2, 3, 4] },
    FI: { lengths: [6, 7, 8, 9, 10], groups: [3, 7] },
    FJ: { lengths: [7], groups: [3, 4] },
    FK: { lengths: [5], groups: [3, 3, 1] },
    FM: { lengths: [7], groups: [3, 4] },
    FO: { lengths: [6], groups: [3, 3, 1] },
    FR: { lengths: [9], groups: [3, 2, 2, 2] },
    GA: { lengths: [8], groups: [2, 2, 2, 2] },
    GB: { lengths: [10], groups: [5, 5] },
    GD: { lengths: [10], groups: [3, 3, 4] },
    GE: { lengths: [9], groups: [3, 3, 3] },
    GF: { lengths: [9], groups: [3, 2, 2, 2] },
    GG: { lengths: [10], groups: [3, 3, 4] },
    GH: { lengths: [9], groups: [2, 3, 4] },
    GI: { lengths: [8], groups: [3, 5] },
    GL: { lengths: [6], groups: [2, 2, 2] },
    GM: { lengths: [7], groups: [3, 4] },
    GN: { lengths: [9], groups: [3, 2, 2, 2] },
    GP: { lengths: [9], groups: [3, 2, 2, 2] },
    GQ: { lengths: [9], groups: [3, 3, 3] },
    GR: { lengths: [10], groups: [2, 4, 4] },
    GT: { lengths: [8], groups: [4, 4] },
    GU: { lengths: [10], groups: [3, 3, 4] },
    GW: { lengths: [9], groups: [3, 3, 3] },
    GY: { lengths: [7], groups: [3, 4] },
    HK: { lengths: [8], groups: [3, 5] },
    HN: { lengths: [8], groups: [4, 4] },
    HR: { lengths: [8, 9], groups: [3, 2, 3] },
    HT: { lengths: [8], groups: [2, 2, 4] },
    HU: { lengths: [9], groups: [2, 3, 4] },
    ID: { lengths: [9, 10, 11, 12], groups: [3, 7] },
    IE: { lengths: [9], groups: [1, 4, 4] },
    IL: { lengths: [9], groups: [2, 3, 4] },
    IM: { lengths: [10], groups: [3, 3, 4] },
    IN: { lengths: [10], groups: [5, 5] },
    IO: { lengths: [7], groups: [3, 4] },
    IQ: { lengths: [10], groups: [3, 3, 4] },
    IR: { lengths: [10], groups: [3, 3, 4] },
    IS: { lengths: [7], groups: [3, 4] },
    IT: { lengths: [9, 10], groups: [3, 6] },
    JE: { lengths: [10], groups: [3, 3, 4] },
    JM: { lengths: [10], groups: [3, 3, 4] },
    JO: { lengths: [9], groups: [3, 6] },
    JP: { lengths: [10], groups: [3, 3, 4] },
    KE: { lengths: [9], groups: [2, 7] },
    KG: { lengths: [9], groups: [4, 5] },
    KH: { lengths: [8, 9], groups: [2, 3, 4] },
    KI: { lengths: [8], groups: [4, 4] },
    KM: { lengths: [7], groups: [3, 2, 2] },
    KN: { lengths: [10], groups: [3, 3, 4] },
    KP: { lengths: [10], groups: [3, 3, 4] },
    KR: { lengths: [9, 10], groups: [1, 4, 4] },
    KW: { lengths: [8], groups: [4, 4] },
    KY: { lengths: [10], groups: [3, 3, 4] },
    KZ: { lengths: [10], groups: [3, 3, 4] },
    LA: { lengths: [9, 10], groups: [2, 2, 2, 3] },
    LB: { lengths: [7, 8], groups: [1, 3, 3] },
    LC: { lengths: [10], groups: [3, 3, 4] },
    LI: { lengths: [7], groups: [3, 2, 2] },
    LK: { lengths: [9], groups: [2, 3, 4] },
    LR: { lengths: [7, 9], groups: [1, 3, 3] },
    LS: { lengths: [8], groups: [4, 4] },
    LT: { lengths: [8], groups: [1, 3, 4] },
    LU: { lengths: [9], groups: [2, 2, 2, 3] },
    LV: { lengths: [8], groups: [2, 3, 3] },
    LY: { lengths: [9], groups: [2, 7] },
    MA: { lengths: [9], groups: [4, 5] },
    MC: { lengths: [8], groups: [2, 3, 3] },
    MD: { lengths: [8], groups: [3, 5] },
    ME: { lengths: [8], groups: [4, 4] },
    MF: { lengths: [9], groups: [3, 3, 3] },
    MG: { lengths: [9], groups: [2, 2, 3, 2] },
    MH: { lengths: [7], groups: [3, 4] },
    MK: { lengths: [8], groups: [1, 3, 4] },
    ML: { lengths: [8], groups: [2, 2, 2, 2] },
    MM: { lengths: [7, 8, 9, 10], groups: [2, 2, 3] },
    MN: { lengths: [8], groups: [2, 2, 4] },
    MO: { lengths: [8], groups: [4, 4] },
    MP: { lengths: [10], groups: [3, 3, 4] },
    MQ: { lengths: [9], groups: [3, 2, 2, 2] },
    MR: { lengths: [8], groups: [2, 2, 2, 2] },
    MS: { lengths: [10], groups: [3, 3, 4] },
    MT: { lengths: [8], groups: [4, 4] },
    MU: { lengths: [8], groups: [4, 4] },
    MV: { lengths: [7], groups: [3, 4] },
    MW: { lengths: [9], groups: [3, 3, 3] },
    MX: { lengths: [10], groups: [2, 4, 4] },
    MY: { lengths: [9, 10], groups: [2, 3, 4] },
    MZ: { lengths: [9], groups: [2, 3, 4] },
    NA: { lengths: [9], groups: [2, 3, 4] },
    NC: { lengths: [6], groups: [2, 2, 2] },
    NE: { lengths: [8], groups: [2, 3, 3] },
    NF: { lengths: [6], groups: [2, 4] },
    NG: { lengths: [10], groups: [3, 3, 4] },
    NI: { lengths: [8], groups: [4, 4] },
    NL: { lengths: [9, 11], groups: [2, 7] },
    NO: { lengths: [8], groups: [3, 2, 3] },
    NP: { lengths: [10], groups: [3, 7] },
    NR: { lengths: [7], groups: [3, 4] },
    NU: { lengths: [4], groups: [3, 3, 1] },
    NZ: { lengths: [8, 9, 10], groups: [3, 2, 3] },
    OM: { lengths: [8], groups: [2, 6] },
    PA: { lengths: [7, 8], groups: [3, 4] },
    PE: { lengths: [9], groups: [3, 3, 3] },
    PF: { lengths: [8], groups: [2, 2, 2, 2] },
    PG: { lengths: [8], groups: [4, 4] },
    PH: { lengths: [10], groups: [4, 6] },
    PK: { lengths: [10], groups: [3, 7] },
    PL: { lengths: [9], groups: [3, 3, 3] },
    PM: { lengths: [6, 9], groups: [2, 2, 2] },
    PR: { lengths: [10], groups: [3, 3, 4] },
    PS: { lengths: [9], groups: [3, 3, 3] },
    PT: { lengths: [9], groups: [2, 3, 4] },
    PW: { lengths: [7], groups: [3, 4] },
    PY: { lengths: [9], groups: [3, 6] },
    QA: { lengths: [8], groups: [4, 4] },
    RE: { lengths: [9], groups: [3, 2, 2, 2] },
    RO: { lengths: [9], groups: [2, 3, 4] },
    RS: { lengths: [8, 9, 10], groups: [3, 3, 4] },
    RU: { lengths: [10], groups: [4, 2, 2, 2] },
    RW: { lengths: [9], groups: [3, 3, 3] },
    SA: { lengths: [9], groups: [4, 5] },
    SB: { lengths: [5], groups: [3, 3, 1] },
    SC: { lengths: [7], groups: [1, 3, 3] },
    SD: { lengths: [9], groups: [2, 3, 4] },
    SE: { lengths: [9], groups: [3, 3, 3] },
    SG: { lengths: [8], groups: [4, 4] },
    SH: { lengths: [5], groups: [3, 3, 1] },
    SI: { lengths: [8], groups: [2, 6] },
    SJ: { lengths: [8], groups: [4, 4] },
    SK: { lengths: [9], groups: [1, 3, 3, 2] },
    SL: { lengths: [8], groups: [2, 6] },
    SM: { lengths: [8], groups: [2, 2, 2, 2] },
    SN: { lengths: [9], groups: [3, 2, 2, 2] },
    SO: { lengths: [7, 8, 9], groups: [1, 6] },
    SR: { lengths: [7], groups: [3, 4] },
    SS: { lengths: [9], groups: [3, 3, 3] },
    ST: { lengths: [7], groups: [3, 4] },
    SV: { lengths: [8], groups: [4, 4] },
    SX: { lengths: [10], groups: [3, 3, 4] },
    SY: { lengths: [9], groups: [2, 3, 4] },
    SZ: { lengths: [8], groups: [4, 4] },
    TA: { lengths: [4], groups: [3, 3, 1] },
    TC: { lengths: [10], groups: [3, 3, 4] },
    TD: { lengths: [8], groups: [2, 2, 2, 2] },
    TG: { lengths: [8], groups: [2, 2, 2, 2] },
    TH: { lengths: [9], groups: [2, 3, 4] },
    TJ: { lengths: [9], groups: [6, 1, 2] },
    TK: { lengths: [4, 5, 6, 7], groups: [3, 3, 1] },
    TL: { lengths: [8], groups: [4, 4] },
    TM: { lengths: [8], groups: [2, 2, 2, 2] },
    TN: { lengths: [8], groups: [2, 3, 3] },
    TO: { lengths: [7], groups: [4, 3] },
    TR: { lengths: [10], groups: [3, 3, 4] },
    TT: { lengths: [10], groups: [3, 3, 4] },
    TV: { lengths: [6, 7], groups: [2, 4] },
    TW: { lengths: [9], groups: [2, 3, 4] },
    TZ: { lengths: [9], groups: [3, 2, 4] },
    UA: { lengths: [9], groups: [3, 3, 3] },
    UG: { lengths: [9], groups: [4, 5] },
    US: { lengths: [10], groups: [3, 3, 4] },
    UY: { lengths: [8], groups: [2, 3, 3] },
    UZ: { lengths: [9], groups: [2, 3, 2, 2] },
    VA: { lengths: [9, 10], groups: [3, 3, 4] },
    VC: { lengths: [10], groups: [3, 3, 4] },
    VE: { lengths: [10], groups: [3, 7] },
    VG: { lengths: [10], groups: [3, 3, 4] },
    VI: { lengths: [10], groups: [3, 3, 4] },
    VN: { lengths: [9], groups: [2, 3, 2, 2] },
    VU: { lengths: [7], groups: [3, 4] },
    WF: { lengths: [6], groups: [2, 2, 2] },
    WS: { lengths: [7, 10], groups: [2, 5] },
    XK: { lengths: [8], groups: [3, 5] },
    YE: { lengths: [9], groups: [3, 3, 3] },
    YT: { lengths: [9], groups: [3, 3, 3] },
    ZA: { lengths: [5, 6, 7, 8, 9], groups: [2, 4] },
    ZM: { lengths: [9], groups: [3, 3, 3] },
    ZW: { lengths: [9], groups: [2, 7] }
}
